9th sprint
Sad-Duck/java-filmorate pull request #1
Opened 2022-09-13 15:17 UTC by Sad-Duck

Первоначальный коммит для отправки на ревью.

2022-09-13 19:58 UTC, chewmag requested changes
Приветствую Алексей!

Требования ТЗ полностью покрыты работой, есть пара косметических штрихов, которые можно рассмотреть к реализации. Также можно подумать над реализацией дополнительного задания. На ваше усмотрение. Присылайте работу на повторную проверку с улучшениями и доп.заданием или без )

2022-09-13 19:58 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/films")
Путь до метода можно переместить в аннотацию RestController, поскольку у всех методов в этом контроллере он одинаковый )

2022-09-13 19:58 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            throw new NotValidException("Id фильма не найдено");
Может завести какой-то NotFoundException ? С точки зрения модели данных film может быть и валидный

2022-09-13 19:58 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @GetMapping("/users")
Здесь тоже пути до методов можно вынести в @RestController

2022-09-13 19:58 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            throw new NotValidException("Id пользователя не найдено");
Тоже правильнее бы кидать другое исключение, не NotValidException

2022-09-14 12:48 UTC, Sad-Duck commented
Реализовал исправления. Пока без доп. задания:)

2022-09-14 18:48 UTC, chewmag approved these changes
Приветствую Алексей!

Улучшения реализованы, можно мерджить PR в main 👍

2022-09-14 19:24 UTC, merged