sprint 11 add database initial commit
Sad-Duck/java-filmorate pull request #3
Opened 2022-11-25 19:40 UTC by Sad-Duck

2022-11-26 10:47 UTC, Frilock requested changes
Добрый день, посмотрел работу. Из комментариев:
1. Переборщили с количеством методов для MPA и Genre, вам достаточно реализовать findAll, findById. 
2. По поводу тестов - все тесты засунуть в 1 класс плохая идея, сделайте для каждой сущности отдельный класс тестов.
3. В своих SQL запросах лучше используйте Join вместо внутренних подзапросов.
4. По желанию, мапперы лучше вынести в отдельный слой приложения - такой код будет проще читать и смотреть.
5. Мелкие комментарии по коду.

2022-11-26 10:47 UTC, Frilock commented on README.md
>  ORDER BY f.duration
Там по ТЗ еще: в файле README.md должна быть ссылка на файл диаграммы.

2022-11-26 10:47 UTC, Frilock commented on README.md
>  SELECT *
.db файлы хотелось бы видеть в gitignore, зачем они на ревью?)

2022-11-26 10:47 UTC, Frilock commented on pom.xml
> +			<version>3.0.0</version>
Версии библиотек, которые вы подключаете в pom файле, правильнее писать в preporties (по аналогии с версией java), поскольку pom файлы могут быть очень большого размера и изменение версии библиотеки может оказаться не такой простой задачей.

2022-11-26 10:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/GenreService.java
> +public class GenreService {
По моему вы переборщили с кол-вом методов для Genre, я в ТЗ вижу: GenreDbStorage, MpaDbStorage - только getById + getAll

2022-11-26 10:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/Mpa/MpaDbStorage.java
> +        String sqlQuery = "INSERT INTO mpa(rating) " +
А зачем переносы делаете? Все нормально в 1 строчку влезает

2022-11-26 10:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/Mpa/MpaDbStorage.java
> +        String sqlQuery = "SELECT * FROM mpa WHERE mpa_id IN (SELECT mpa_id FROM films WHERE film_id = ?)";
Я бы посоветовал попробовать запрос переделать на использование Join вместо подзапроса

2022-11-26 10:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/Mpa/MpaDbStorage.java
> +    private static Mpa makeMpa(ResultSet rs, int rownum) throws SQLException {
Было бы здорово, чтобы вы данные мапперы, вынесли в отдельные классы, такой код был более читаемым и в нем было бы легче ориентироваться. Но на Ваше усмотрение

2022-11-26 10:47 UTC, Frilock commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
>  class FilmorateApplicationTests {
Реализуйте для каждой сущности свои тесты, все в 1 кучу запихивать плохая идея. В классе с 1к+ строк разбираться довольно трудно

2022-11-26 10:47 UTC, Frilock commented on src/main/resources/beforeTest.sql
> +DELETE FROM LIKES;
Можно просто Drop All Objects

2022-11-26 10:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/model/StorageData.java
> +    Long id;
А зачем модификатор убираете? Сделайте protected

2022-11-26 10:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(@Qualifier("filmDbStorage") FilmStorage storage,
Кстати раз вы удаляете InMemory Классы, то вам по сути и квалифаер не нужен =) Реализация то у интерфейса одна

2022-11-26 10:47 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        LocalDate releaseDate = rs.getDate("release_date").toLocalDate();
rs.getDate("release_date") - null не вернет? Иначе NPE получите

2022-11-28 16:23 UTC, Sad-Duck commented
Здравствуйте, внес все исправления кроме NPE в методе rs.getDate("release_date"), я не понимаю где его ловить? В бд у поля стоит ограничение not null. Спасибо!

2022-11-28 18:31 UTC, Frilock requested changes
Добрый вечер, еще пару комментариев написал, посмотрите пожалуйста. Будут вопросы пишите

2022-11-28 18:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        public List<Film> getByGenre(long genreId) {
Я вот смотрю ваше ТЗ и никак понять не могу для чего этот ендпойт, вроде как его у вас нет в ТЗ

2022-11-28 18:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/Mpa/MpaDbStorage.java
> +package ru.yandex.practicum.filmorate.storage.Mpa;
Пакет правильнее строчными назвать - mpa

2022-11-28 18:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/ModelMapper.java
> +        LocalDate releaseDate = rs.getDate("release_date").toLocalDate();
А тут не нужно проверять, что rs.getDate("release_date") null не вернет?

2022-11-28 18:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/ModelMapper.java
> +@Component
А зачем компонентом делать, если у Вас все методы статические и вы можете их вызывать без создания экземпляра класса?

2022-11-28 18:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/ModelMapper.java
> +        LocalDate birthday = rs.getDate("BIRTHDAY").toLocalDate();
А тут не нужно проверять, что rs.getDate("release_date") null не вернет?

2022-11-28 18:31 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +                "SELECT * FROM USERS WHERE USER_ID IN " +
А мы можем JOINами обойтись, без внутренних подзапросов?

2022-11-28 18:31 UTC, Frilock commented on src/main/resources/beforeTest.sql
> +    GENRE    VARCHAR
Странное название колонки - name? Мне кажется нужно переименовать

2022-11-28 18:31 UTC, Frilock commented on src/main/resources/schema.sql
> +    GENRE    VARCHAR
Надо бы переименовать

2022-11-28 21:25 UTC, Sad-Duck commented on src/main/resources/beforeTest.sql
> +    GENRE    VARCHAR
Если речь про колонку имени у фильмов (тут не показывает к какой строчке коммент), то можно было бы переименовать на, например, "title", но постман не пропустит, ему надо именно "name"

2022-11-28 21:25 UTC, Sad-Duck commented on src/main/resources/schema.sql
> +    GENRE    VARCHAR
аналогично с замечанием выше:)

2022-11-28 21:30 UTC, Sad-Duck commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        public List<Film> getByGenre(long genreId) {
Случайно его пропустил после первого ревью. 
А вообще, это уже моё творчество скорее было, мне кажется люди часто ищут фильмы по жанрам:)

2022-11-29 09:02 UTC, Frilock commented on src/main/resources/beforeTest.sql
> +    GENRE    VARCHAR
Так да, но у Вас она называется - Genre, я тут криво комментарий написал Вам. Ладно оставим пока так, потом можете переименовать.

2022-11-29 09:03 UTC, Frilock approved these changes
Работу принял, на комментарий про название поля ответил =) Успехов дальше

2022-11-30 13:36 UTC, merged